"""empty message

Revision ID: 6218e89ce9a8
Revises: 93342d5f15d4
Create Date: 2019-02-23 19:53:21.816678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6218e89ce9a8'
down_revision = '93342d5f15d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_data', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_data', type_='unique')
    # ### end Alembic commands ###
