"""empty message

Revision ID: 93342d5f15d4
Revises: a0a279efb970
Create Date: 2019-02-23 19:38:40.161055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93342d5f15d4'
down_revision = 'a0a279efb970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('dob', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
